return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shellcheck",
      "shfmt",
      "flake8",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "hadolint",
      "js-debug-adapter",
      "lua-language-server",
      "markdown-toc",
      "markdownlint-cli2",
      "marksman",
      "prettier",
      "shfmt",
      "stylua",
      "tailwindcss-language-server",
      "vtsls",
      "nginx-language-server",
      "nginx-config-formatter",
      -- "buf",
      "protols",
      "protolint",
    },
  },
}
