alias cls='clear'
alias v='nvim .'
alias vi='nvim'
alias so='source'
alias chrome='/mnt/c/Program\ Files/Google/Chrome/Application/chrome.exe'
alias nvimrc='cd ~/.config/nvim/ && nvim .'
alias cdf='cd $(find . -type d -print | fzf --height=40% --layout=reverse )'
alias vf='cdf && nvim .'
