unbind r 
bind r source-file ~/.config/tmux/tmux.conf

set -g prefix C-b

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind r source-file ~/.config/tmux/tmux.conf \

bind | split-window -h

set -g default-terminal "xterm-256color"

set -g allow-passthrough all
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off

set -g mouse on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.1.3'

run ~/.config/tmux/plugins/tpm/tpm
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g status-position bottom


set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text " local"
set -g @catppuccin_window_current_text " #W"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-left "#{E:@catppuccin_status_session}"
set -ag status-left " "
set -g status-right "#{E:@catppuccin_status_application}"


